name: Build & test whl

on: [push]

jobs:

  build-package:
    name: Build & Verify Package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build and Inspect Package
        uses: hynek/build-and-inspect-python-package@v2
        id: baipp

    outputs:
      python-versions: ${{ steps.baipp.outputs.supported_python_classifiers_json_array }}

  testwheel:
    name: Test Built Wheel
    runs-on: ubuntu-latest
    needs: build-package
    strategy:
      max-parallel: 4
      matrix:
        python-version:
            - "3.10"
            - "3.11"
            - "3.12"
            - "3.13"

    steps:
      - name: Download Pre-built Package
        uses: actions/download-artifact@v4
        with:
          name: Packages
          path: dist

      - name: Extract Source Tarball
        run: tar xf dist/*.tar.gz --strip-components=1

      - name: Remove Source Code
        run: rm -R cbar

      - name: Set Up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Tox
        run: python -Im pip install tox

      - name: Run Tox on Wheel
        run: python -Im tox run --installpkg dist/*.whl
