name: Upload Python Package to PyPi.org

on:
  release:
    types: [published]

jobs:
  build-package:
    name: Build & Verify Package
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      attestations: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build and Inspect Package
        uses: hynek/build-and-inspect-python-package@v2
        with:
          attest-build-provenance-github: 'true'

  deploy:
    name: Publish to PyPI
    environment:
      name: pypi
      url: https://pypi.org/project/cbar-rates/
    runs-on: ubuntu-latest
    needs: build-package
    permissions:
      id-token: write
      attestations: write
    steps:
      - name: Download Built Package
        uses: actions/download-artifact@v4
        with:
          name: Packages
          path: dist

      - name: Validate Package Contents
        run: tar -tf dist/*.tar.gz

      - name: Upload Package to PyPI
        uses: pypa/gh-action-pypi-publish@v1.10.1
